In [1]:
## Task 1:


1. Write a function to compute 5/0 and use try/except to catch the exceptions. 

In [13]:
try:
    c=5/0
    print(c)
except:
    try:
        a=3/0
        print(a)
    except:
        print('zero error problem')
    

zero error problem


2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 

In [2]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"] 

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i,j,k)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [35]:
## TAsk2

1. Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.  
 

In [65]:
import numpy as np
    
a=np.array([1,2,3,4,5])
out=np.array([x**i for x in a for i in range(len(a))]).reshape(a.size,len(a))
out1=np.array([x**(n-1-i) for x in a for i in range(len(a))]).reshape(a.size,len(a))

print('increasing= true\n')
print(out,'\n')
print('increasing=false\n')
print(out1)

increasing= true

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 

increasing=false

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
